# Generated by Django 2.0.6 on 2018-06-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soda',
            options={'ordering': ('_id',)},
        ),
    ]
