# Generated by Django 2.0.6 on 2018-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soda', '0002_auto_20180607_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
